services:
  frontend:
    container_name: movies-palettes-frontend
    image: ghcr.io/bolinocroustibat/movies-palettes-frontend:${TAG:-latest}
    build: .
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./static:/app/static
    environment:
      - VITE_ENV=${VITE_ENV}
      # This variable need to be set:
      # - In .env for local development
      # - As GitHub vars/secrets for workflows
      # - MOVIES_SQLITE_URL=${MOVIES_SQLITE_URL}
