name: Update Movies Data

on:
  workflow_dispatch:

jobs:
  update-movies-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Adding server to known hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Download and test movies data on server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "\
            mkdir -p ${{ secrets.SERVER_PATH }} \
            && wget -O ${{ secrets.SERVER_PATH }}/movies.sqlite '${{ vars.MOVIES_SQLITE_URL }}' \
            && touch -m ${{ secrets.SERVER_PATH }}/movies.sqlite \
            && echo 'Number of movies: '\$(jq -r '.movies | length' ${{ secrets.SERVER_PATH }}/movies.sqlite) \
            && echo 'Last updated: '\$(jq .last_updated ${{ secrets.SERVER_PATH }}/movies.sqlite)"
