name: Update Movies Data

on:
  workflow_dispatch:

jobs:
  update-movies-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Adding server to known hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Download movies DB to static directory
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "wget -O ${{ secrets.SERVER_PATH }}/static/movies.db '${{ vars.MOVIES_SQLITE_URL }}'"

      - name: Test if the downloaded file is a valid SQLite database
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd ${{ secrets.SERVER_PATH }} && bun -e 'try { const { Database } = require(\"bun:sqlite\"); const db = new Database(\"${{ secrets.SERVER_PATH }}/static/movies.db\", { readonly: true }); const count = db.query(\"SELECT COUNT(*) as count FROM movies\").get().count; console.log(\"Database OK:\", count, \"movies found\"); process.exit(0); } catch (e) { console.error(\"Invalid database file:\", e); process.exit(1); }'"
